# File Processing

#### File Paths:
-   Absolute Paths - Beings at the root folder. Starts at the base of your computer.
    -   ex: `/Volumes/ExtHD/PerScholas/RTT-36/385/385.3/notes/notes.ipynb`
-   Relative paths - Path is relative to the current (working) directory
    -   ex: `./notes.ipynb`

#### File Path Symbols
-   `/` - divider between folders/files
-   `.` - currect directory
-   `..` - One directory up the chain

#### Opening Files
-   `open(file_path, mode)` - function

#### File modes
-   `r` - read - if file does not exists (FileNotFoundError)
-   `w` - write - if file doesnt exist, it creates a new file
-   `a` - append - if file doesnt exist, it creates a new file
-   `x` - exlusive creation - if file doesnt exist, it creates a new file
-   `b` - binary
-   `t` - text
-   `+` - read/write

In [7]:
f = open('data/my_file.txt', mode='r') # opens the file

print(f.read()) # reads the file

f.close() # Always close your file to prevent extra resources and breaking of files.

FileNotFoundError: [Errno 2] No such file or directory: 'data/my_file.txt'

#### Error Handling w/ Try: Except: Finally
-   `try:` - this block is code we want to run
-   `except:` - raise exceptions for errors we run into. Code to run if we get an error
-   `finally:` - code we run no matter what happens. errors or not

In [ ]:
try:
    f = open('data/my_file.txt', mode='r')

    print(f.read())

except Exception as e: # if an error, put in variable 'e' and print error to logs (terminal)
    print(f'❌ Error: {e}')

finally:
    f.close()

Daryyl was hereDaryyl was here
Daryyl was here
Daryyl was here
Daryyl was here
Daryyl was here



In [ ]:
# if opening file with 'with', all code goes into the with code block and the file auto closes at the end of the block
with open('data/my_file.txt', 'r') as f:
    print(f.read())

Hello World!


In [ ]:
def write_to_file(str, file_path):
    try:
        with open(file_path, 'w') as f:
            f.write(str + '\n')
            
        print('Success')
    except Exception as e:
        print(f'❌ Error: {e}')

In [ ]:
write_to_file('Dylan was here', 'data/my_file.txt')

Success


In [ ]:
write_to_file('Darryl was here', 'data/my_file.txt')

Success


In [ ]:
def append_to_file(str, file_path):
    try:
        with open(file_path, 'a') as f:
            f.write(str + '\n')
            
        print('Success')
    except Exception as e:
        print(f'❌ Error: {e}')

In [ ]:
import numpy as np

print('Numpy Version: ', np.__version__)

In [ ]:
one_to_100 = np.arange(100)

print(one_to_100)

# array from 1 - 30 not including 30
one_thirty = np.arange(1, 30)
print(one_thirty)

# array from 10-20 by 2
ten_twenty = np.arange(10, 20, 2)
print(ten_twenty)

# array from -3 -10 10 by 4, verify dtype is int
print(np.arange(-3, 10, 4, dtype=int))

NameError: name 'np' is not defined

In [ ]:
from numpy import random

# Generate a random array of 10 numbers between 0-1
data = random.rand(10)

print(data)

# Generate an array of random numbers with a normal distribution
normal_dist = random.randn(10)

print(normal_dist)

# Normally distributed Matrix, 3 rows, 2 records in each row
normal_dist_matrix = random.randn(3, 2)

print(normal_dist_matrix)

In [ ]:
# Define a list
elements = ['a', 'b', 'c', 'd', 'e', 'f']

# Choose a random value from the list
random_sample = random.choice(elements)

print(random_sample)

print('Before Shuffle', elements)
random.shuffle(elements)
print('After Shuffle', elements) # shuffling elements of array for randomness

In [ ]:
# Define a list of dishes on the menu
menu = [
    "Spaghetti Carbonara",
    "Chicken Alfredo",
    "Margherita Pizza",
    "Cheeseburger",
    "Caesar Salad",
    "Fish and Chips",
    "Pad Thai",
    "Sushi Platter",
    "Vegetable Stir-Fry",
    "Grilled Salmon"
]

# Function to suggest a random dish
def suggest_dish():
    random_dish = random.choice(menu)
    return random_dish

# Main program
print("Welcome to the Restaurant Menu Randomizer!")
print("If you're undecided about what to order, let us help you decide.")

while True:
    user_input = input("Press enter to get a random dish suggestion (or type 'quit' to exit): ")

    if user_input.lower() == 'quit':
        print("Thank you for using the Restaurant Menu Randomizer. Enjoy your meal!")
        break

    suggested_dish = suggest_dish()
    print("Randomly suggested dish:", suggested_dish)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

element = arr[3]
print('Element: ', element)

slice = arr[1:4]
print('Slice: ', slice)

print(arr)

In [ ]:
# Arithmetic and NumPy Arrays
# Arithmetic with arrays and scalar values compute element-wise (PER ELEMENT, for each element)
arr = np.array([1, 2, 3])
arr2 = np.array([9, 8, 7])

print(arr + 1) #[2, 3, 4]
print(arr * 3) #[3, 6, 9]
print(arr / 2) # [0.5, 1.0, 1.5]

print(arr + arr2) # [10, 10, 10] added elements at the same index together.

In [ ]:
# NumPy Aggregations
arr = np.array([1, 2, 3, 4, 5])

sum = np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
stDev = np.std(arr)
min = np.min(arr)
max = np.max(arr)

print('Sum: ', sum)
print('Avg: ', mean)
print('Median: ', median)
print('Standard Deviation: ', stDev)
print('Min: ', min)
print('Max: ', max)

In [ ]:
# Logical Operators AND, OR NOT
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
print('Logical And') # compare each element in a list
print(np.logical_and(a, b))

print('\nLogical Or') # compare each element in a list
print(np.logical_or(a, b))

c = np.array([True, True, False, False])
print(np.logical_not(c)) # Flips the boolean value

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
c = np.array([2, 3, 4, 5])

print(np.array_equal(a, b)) # compares the entire array looking for differences.

print(np.array_equal(a, c))

In [ ]:
{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e51ef744",
   "metadata": {},
   "source": [
    "# NumPy Library (Numerical Python)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e2bfd040",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Numpy Version:  2.5.3\n"
     ]
    }
   ],
   "source": [
    "import numpy as np # common alias for numpy\n",
    "\n",
    "print('Numpy Version: ', np.__version__)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "504958f7",
   "metadata": {},
   "source": [
    "### Properties of NumPy\n",
    "-   Gives us access to the NumPy `Array` object.\n",
    "-   Array manipulation\n",
    "-   Array aggregation.\n",
    "-   Data analysis, machine learning tasks\n",
    "-   Processing Numerical data effeciently\n",
    "-   Data Cleaning/Wrangling\n",
    "-   When using Arrays they should be a single data type (homogeneous data)\n",
    "-   `ndarray` - data type for a NumPy Array"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d826c1ad",
   "metadata": {},
   "source": [
    "#### Installing NumPy\n",
    "-   `pip install numpy`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9f489ced",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3 4 5 6]\n",
      "[2 4]\n"
     ]
    }
   ],
   "source": [
    "# single dimensional arrays (Vector)\n",
    "\n",
    "# Array type are determined automatically by numpy\n",
    "# Declare a numpy array with list, tuple, range (sequence)\n",
    "\n",
    "oneD = np.array(\n",
    "    [1, 2, 3, 4, 5, 6]\n",
    ")\n",
    "\n",
    "print(oneD)\n",
    "print(oneD[1:4:2])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1846bf70",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[1 2 3]\n",
      " [3 4 6]\n",
      " [7 8 9]]\n"
     ]
    }
   ],
   "source": [
    "# Two dimensional array (Matrix) Grid. Similar to a table\n",
    "twoD = np.array(\n",
    "    [\n",
    "        [1, 2, 3],\n",
    "        [3, 4, 6],\n",
    "        [7, 8, 9]\n",
    "    ]\n",
    ")\n",
    "\n",
    "print(twoD)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "105362f0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[[1 2]\n",
      "  [3 4]]\n",
      "\n",
      " [[5 6]\n",
      "  [7 8]]]\n"
     ]
    }
   ],
   "source": [
    "# Three dimensional Array (Tensor). set of matrices\n",
    "threeD = np.array(\n",
    "    [\n",
    "        [\n",
    "            [1, 2],\n",
    "            [3, 4]\n",
    "        ],\n",
    "        [\n",
    "            [5, 6],\n",
    "            [7, 8]\n",
    "        ]\n",
    "    ]\n",
    ")\n",
    "\n",
    "print(threeD)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "f0995952",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'numpy.ndarray'>\n",
      "<class 'numpy.int64'>\n"
     ]
    }
   ],
   "source": [
    "# N-dimensional - ndarray\n",
    "# zero - based indexing\n",
    "print(type(oneD))\n",
    "\n",
    "print(type(oneD[3]))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6bd073b0",
   "metadata": {},
   "source": [
    "### Declaring Arrays in Python\n",
    "-   `.array()` - delarcing simple arrays with lists, tuples, ranges\n",
    "-   `.arange()` - rangle function to create an array.\n",
    "    -   syntax: `np.arange(start, stop, step, dtype)`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "1e99a76a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23\n",
      " 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47\n",
      " 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71\n",
      " 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95\n",
      " 96 97 98 99]\n",
      "[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24\n",
      " 25 26 27 28 29]\n",
      "[10 12 14 16 18]\n",
      "[-3  1  5  9]\n"
     ]
    }
   ],
   "source": [
    "one_to_100 = np.arange(100)\n",
    "\n",
    "print(one_to_100)\n",
    "\n",
    "# array from 1 - 30 not including 30\n",
    "one_thirty = np.arange(1, 30)\n",
    "print(one_thirty)\n",
    "\n",
    "# array from 10-20 by 2\n",
    "ten_twenty = np.arange(10, 20, 2)\n",
    "print(ten_twenty)\n",
    "\n",
    "# array from -3 -10 10 by 4, verify dtype is int\n",
    "print(np.arange(-3, 10, 4, dtype=int))"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1ec07a0e",
   "metadata": {},
   "source": [
    "#### NumPy Array Attributes - Array descriptors\n",
    "-   `array.shape` - tuple with the num of rows and columns\n",
    "-   `array.size` - total number of elements (records) in array\n",
    "-   `array.dtype` - data type of arrays\n",
    "-   `array.ndim` - number of dimensions\n",
    "-   can be used with pandas DF"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "47be8e15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3 4 5 6]\n",
      "(6,)\n",
      "6\n",
      "int64\n",
      "1\n"
     ]
    }
   ],
   "source": [
    "print(oneD)\n",
    "print(oneD.shape)\n",
    "print(oneD.size)\n",
    "print(oneD.dtype)\n",
    "print(oneD.ndim)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0c50b620",
   "metadata": {},
   "source": [
    "### Random Numbers in NumPy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "59965f39",
   "metadata": {},
   "outputs": [],
   "source": [
    "from numpy import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "0b5f0736",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.010375418478840936\n",
      "1.6035969796948002\n"
     ]
    }
   ],
   "source": [
    "# Generate random num between 0-1\n",
    "print(random.rand())\n",
    "\n",
    "# Generate random numbers with normal distribution\n",
    "print(random.randn())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e1f579ba",
   "metadata": {},
   "source": [
    "### NumPy Operations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "id": "2a546f59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Element:  4\n",
      "Slice:  [2 3 4]\n",
      "[1 2 3 4 5]\n"
     ]
    }
   ],
   "source": [
    "# Array Access\n",
    "arr = np.array([1, 2, 3, 4, 5])\n",
    "\n",
    "element = arr[3]\n",
    "print('Element: ', element)\n",
    "\n",
    "slice = arr[1:4]\n",
    "print('Slice: ', slice)\n",
    "\n",
    "print(arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "ad5228f8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[2 3 4]\n",
      "[3 6 9]\n",
      "[0.5 1.  1.5]\n",
      "[10 10 10]\n"
     ]
    }
   ],
   "source": [
    "# Arithmetic and NumPy Arrays\n",
    "# Arithmetic with arrays and scalar values compute element-wise (PER ELEMENT, for each element)\n",
    "arr = np.array([1, 2, 3])\n",
    "arr2 = np.array([9, 8, 7])\n",
    "\n",
    "print(arr + 1) #[2, 3, 4]\n",
    "print(arr * 3) #[3, 6, 9]\n",
    "print(arr / 2) # [0.5, 1.0, 1.5]\n",
    "\n",
    "print(arr + arr2) # [10, 10, 10] added elements at the same index together."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "id": "975afd7d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sum:  15\n",
      "Avg:  3.0\n",
      "Median:  3.0\n",
      "Standard Deviation:  1.4142135623730951\n",
      "Min:  1\n",
      "Max:  5\n"
     ]
    }
   ],
   "source": [
    "# NumPy Aggregations\n",
    "arr = np.array([1, 2, 3, 4, 5])\n",
    "\n",
    "sum = np.sum(arr)\n",
    "mean = np.mean(arr)\n",
    "median = np.median(arr)\n",
    "stDev = np.std(arr)\n",
    "min = np.min(arr)\n",
    "max = np.max(arr)\n",
    "\n",
    "print('Sum: ', sum)\n",
    "print('Avg: ', mean)\n",
    "print('Median: ', median)\n",
    "print('Standard Deviation: ', stDev)\n",
    "print('Min: ', min)\n",
    "print('Max: ', max)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "id": "bcc4f372",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Before Transpose\n",
      "[[1 2 3]\n",
      " [4 5 6]]\n",
      "\n",
      "Transposed Matrix\n",
      "[[1 4]\n",
      " [2 5]\n",
      " [3 6]]\n",
      "\n",
      "Reshaped Matrix\n",
      "[[1 2]\n",
      " [3 4]\n",
      " [5 6]]\n"
     ]
    }
   ],
   "source": [
    "# Transpose or Reshape\n",
    "matrix = np.array(\n",
    "    [\n",
    "        [1, 2, 3],\n",
    "        [4, 5, 6]\n",
    "    ]\n",
    ")\n",
    "\n",
    "print('Before Transpose')\n",
    "print(matrix)\n",
    "# Tranpose, pivot table 90 degrees\n",
    "transpose_matrix = matrix.T\n",
    "print('\\nTransposed Matrix')\n",
    "print(transpose_matrix)\n",
    "\n",
    "\n",
    "reshaped_matrix = matrix.reshape(3, 2)\n",
    "\n",
    "print('\\nReshaped Matrix')\n",
    "print(reshaped_matrix)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b2ebce89",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Logical And\n",
      "[ True False False False]\n",
      "\n",
      "Logical Or\n",
      "[ True  True  True False]\n"
     ]
    }
   ],
   "source": [
    "# Logical Operators AND, OR NOT\n",
    "a = np.array([True, True, False, False])\n",
    "b = np.array([True, False, True, False])\n",
    "print('Logical And') # compare each element in a list\n",
    "print(np.logical_and(a, b))\n",
    "\n",
    "print('\\nLogical Or') # compare each element in a list\n",
    "print(np.logical_or(a, b))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 101,
   "id": "111483ba",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[False False  True  True]\n"
     ]
    }
   ],
   "source": [
    "c = np.array([True, True, False, False])\n",
    "print(np.logical_not(c)) # Flips the boolean value"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "id": "4769d95b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n",
      "False\n"
     ]
    }
   ],
   "source": [
    "a = np.array([1, 2, 3, 4])\n",
    "b = np.array([1, 2, 3, 4])\n",
    "c = np.array([2, 3, 4, 5])\n",
    "\n",
    "print(np.array_equal(a, b)) # compares the entire array looking for differences.\n",
    "\n",
    "print(np.array_equal(a, c))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "id": "fdb405e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[ -8  -1   3   6  13  14  23  32 100]\n"
     ]
    }
   ],
   "source": [
    "# Sorting Arrays\n",
    "a = np.array([3, 13, 6, 23, 14, 100, -1, -8, 32])\n",
    "\n",
    "print(np.sort(a))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "id": "ea26b8af",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "True\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "# Searching\n",
    "\n",
    "# Membership operators\n",
    "print(12 not in a)\n",
    "print(3 in a)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4221fcbb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "7\n",
      "5\n"
     ]
    }
   ],
   "source": [
    "b = np.array([3, 13, 6, 23, 14, 100, -1, -8, 32])\n",
    "print(np.argmin(b)) # return the index number of the lower/minimum value\n",
    "\n",
    "print(np.argmax(b)) # return the index number of the max value"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 123,
   "id": "f0f5fbf0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5\n",
      "2\n"
     ]
    }
   ],
   "source": [
    "# count_nonzero() - counts non-zero elements\n",
    "a = np.array([0, 1, 2, 0, 13, 15, 0, 6])\n",
    "\n",
    "print(np.count_nonzero(a))\n",
    "\n",
    "b = np.array([\n",
    "    [1, 2, 0],\n",
    "    [0, 0, 0]\n",
    "])\n",
    "\n",
    "print(np.count_nonzero(b))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d964cb84",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1 2 3 4 5 6 7 8]\n"
     ]
    }
   ],
   "source": [
    "# concatenate() - combines multiple arrays into one array\n",
    "\n",
    "a = np.array([1, 2, 3, 4])\n",
    "b = np.array([5, 6, 7, 8])\n",
    "c = np.concatenate((a, b), axis=0)\n",
    "\n",
    "print(c)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv (3.12.13)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}


In [ ]:
data = np.array([85, 90, 78, 92, 88, 85, 95])

# Calculate the mean - save in variables
mean = np.mean(data)
# Calculate the median - save in variables
median = np.median(data)
# Calculate the standard deviation - save in variables
stDev = np.std(data)
# Calculate the range - save in variables
range = np.max(data) - np.min(data)
# Calculate the variance - save in variables
variance = np.var(data)

#Print out your values
print(f'Mean: {mean:.2f}')
print('Median: ', median)
print('StDev: ', stDev)
print('Range: ', range)
print('Variace: ', variance)