# Datetime modules
-   `datetime` - built-in module for datetime functionality
-   `calendar` - built-in module, calendar related functionality
-   `time` - module for time functionality

In [9]:
from datetime import date, datetime, time

In [10]:
# Create date object
last_year = date(2025, 9, 18)
print(last_year)

2025-09-18


In [11]:
today_to_the_sec = datetime.now()
print(today_to_the_sec)
print(today_to_the_sec.year)
print(today_to_the_sec.month)
print(today_to_the_sec.day)
print(today_to_the_sec.hour)
print(today_to_the_sec.minute)
print(today_to_the_sec.second)
print(today_to_the_sec.microsecond)
print(today_to_the_sec.tzinfo)

print(today_to_the_sec.timestamp())

2026-09-23 07:18:22.771831
2026
9
23
7
18
22
771831
None
1790162302.771831


In [12]:
time_ish = time(hour=12, minute=45, second=45)
print(time_ish)

12:45:45


-   strftime() - function allows the formatting of dates/times in python

In [13]:
import numpy as np

print('Numpy Version: ', np.__version__)

Numpy Version:  2.5.3


In [14]:
one_to_100 = np.arange(100)

print(one_to_100)

# array from 1 - 30 not including 30
one_thirty = np.arange(1, 30)
print(one_thirty)

# array from 10-20 by 2
ten_twenty = np.arange(10, 20, 2)
print(ten_twenty)

# array from -3 -10 10 by 4, verify dtype is int
print(np.arange(-3, 10, 4, dtype=int))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[10 12 14 16 18]
[-3  1  5  9]


In [15]:
from numpy import random

# Generate a random array of 10 numbers between 0-1
data = random.rand(10)

print(data)

# Generate an array of random numbers with a normal distribution
normal_dist = random.randn(10)

print(normal_dist)

# Normally distributed Matrix, 3 rows, 2 records in each row
normal_dist_matrix = random.randn(3, 2)

print(normal_dist_matrix)

[0.62658102 0.32692744 0.82999864 0.16507136 0.38632314 0.58924814
 0.55217681 0.73663737 0.84050706 0.52772625]
[ 1.5090292   0.88989746  0.07853595  2.51047356  0.57108561 -0.4671258
  0.58743775  0.58488879 -0.37532739 -1.08197693]
[[-0.08202671  0.51998489]
 [-0.1722408  -0.00606489]
 [ 0.8826836   0.06128932]]


In [16]:
# Define a list
elements = ['a', 'b', 'c', 'd', 'e', 'f']

# Choose a random value from the list
random_sample = random.choice(elements)

print(random_sample)

print('Before Shuffle', elements)
random.shuffle(elements)
print('After Shuffle', elements) # shuffling elements of array for randomness

d
Before Shuffle ['a', 'b', 'c', 'd', 'e', 'f']
After Shuffle ['d', 'f', 'c', 'b', 'a', 'e']


In [17]:
# Define a list
elements = ['a', 'b', 'c', 'd', 'e', 'f']

# Choose a random value from the list
random_sample = random.choice(elements)

print(random_sample)

print('Before Shuffle', elements)
random.shuffle(elements)
print('After Shuffle', elements) # shuffling elements of array for randomness

d
Before Shuffle ['a', 'b', 'c', 'd', 'e', 'f']
After Shuffle ['b', 'c', 'e', 'd', 'f', 'a']


In [18]:
arr = np.array([1, 2, 3, 4, 5])

element = arr[3]
print('Element: ', element)

slice = arr[1:4]
print('Slice: ', slice)

print(arr)

Element:  4
Slice:  [2 3 4]
[1 2 3 4 5]
